-- Create allergen_master table
CREATE TABLE IF NOT EXISTS allergen_master (
  allergen_id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Insert some sample allergen data
INSERT INTO allergen_master (name) VALUES 
('Milk'),
('Eggs'),
('Fish'),
('Shellfish'),
('Tree Nuts'),
('Peanuts'),
('Wheat'),
('Soybeans'),
('Sesame'),
('Mustard'),
('Celery'),
('Lupin'),
('Sulfites'),
('Gluten'),
('Lactose'),
('Histamine'),
('Monosodium Glutamate (MSG)'),
('Aspartame'),
('Saccharin'),
('Sucralose'),
('Acesulfame Potassium'),
('Neotame'),
('Advantame'),
('Cyclamate'),
('Steviol Glycosides'),
('Erythritol'),
('Xylitol'),
('Mannitol'),
('Sorbitol'),
('Maltitol'),
('Isomalt'),
('Lactitol'),
('Polydextrose'),
('Inulin'),
('Fructooligosaccharides (FOS)'),
('Galactooligosaccharides (GOS)'),
('Resistant Starch'),
('Beta-Glucan'),
('Pectin'),
('Gum Arabic'),
('Guar Gum'),
('Xanthan Gum'),
('Carrageenan'),
('Agar'),
('Alginate'),
('Pectins'),
('Cellulose'),
('Hemicellulose'),
('Lignin'),
('Chitin'),
('Chitosan'); 